export const videos = [
  {
    id: "1",
    title: "Think Box, Play Box, Decision LIne",
    src: "3704.mp4",
    ratio: "9/16",
    tags: "hitting,mentality",
    duration: "1:59",
    slug: "think-box-play-box-decision-line-1",
    filename: "3704.mp4",
    org_source: "https://www.instagram.com/reel/DVbbC-HETS8/",
    date_added: "4/2/2026",
  },
  {
    id: "2",
    title: "Owl Focus - from Cute to Apex Predator",
    src: "3652.mp4",
    ratio: "9/16",
    tags: "focus",
    duration: "0:14",
    slug: "owl-focus-from-cute-to-apex-predator-2",
    filename: "3652.mp4",
    org_source: "https://www.instagram.com/reel/DVbDTKmE4P9/",
    date_added: "4/2/2026",
  },
  {
    id: "3",
    title: "Dogs Laser-Like Focus Amid Distractions",
    src: "2426.mp4",
    ratio: "9/16",
    tags: "focus",
    duration: "0:20",
    slug: "dogs-laser-like-focus-amid-distractions-3",
    filename: "2426.mp4",
    org_source: "https://www.instagram.com/reel/DVVp9o-gaRa/",
    date_added: "4/2/2026",
  },
  {
    id: "4",
    title: "Holding the Dumbbell on the Lead Arm",
    src: "3105.mp4",
    ratio: "9/16",
    tags: "drill,ballance,hitting",
    duration: "0:18",
    slug: "holding-the-dumbbell-on-the-lead-arm-4",
    filename: "3105.mp4",
    org_source: "https://www.instagram.com/reel/DUbA6nIjtr6/",
    date_added: "4/2/2026",
  },
  {
    id: "5",
    title:
      "How to Teach a Young Baseball Player to Catch a Baseball (WITHOUT BEING AFRAID/SCARED OF THE BALL!)",
    src: "https://www.youtube.com/watch?v=z38XY0UoU7o",
    ratio: "16/9",
    tags: "simple catch",
    duration: "18:05",
    slug: "how-to-teach-a-young-baseball-player-to-catch-a-baseball-without-being-afraid-scared-of-the-ball-5",
    filename: "5327.mp4",
    org_source: "https://www.youtube.com/watch?v=z38XY0UoU7o",
    date_added: "4/2/2026",
  },
  {
    id: "6",
    title: "How to Fix Bat Drag",
    src: "https://www.youtube.com/watch?v=6dfjV84ZN1g",
    ratio: "16/9",
    tags: "batting,drills,bat drag",
    duration: "11:38",
    slug: "how-to-fix-bat-drag-6",
    filename: "9941.mp4",
    org_source: "https://youtu.be/6dfjV84ZN1g",
    date_added: "4/2/2026",
  },
  {
    id: "7",
    title: "95 MPH Pitching Mechanics",
    src: "https://www.youtube.com/shorts/NIgBj2JhEEM",
    ratio: "9/16",
    tags: "pitching,mechanics,slowmo",
    duration: "0:12",
    slug: "95-mph-pitching-mechanics-7",
    org_source: "https://www.youtube.com/shorts/NIgBj2JhEEM",
    date_added: "4/3/2026",
  },
  {
    id: "8",
    title: "Paul Skenes Pitching Mechanics Slow Motion",
    src: "https://www.youtube.com/shorts/hrnXAvlE1ng",
    ratio: "9/16",
    tags: "pitching,mechanics,slowmo",
    duration: "0:37",
    slug: "paul-skenes-pitching-mechanics-slow-motion-8",
    org_source: "https://www.youtube.com/shorts/hrnXAvlE1ng",
    date_added: "4/3/2026",
    player: "Paul Skenes",
  },
  {
    id: "9",
    title: "Max Scherzer Ground Force Application",
    src: "https://www.youtube.com/shorts/MaYpO3s0LwQ",
    ratio: "1/1",
    tags: "pitching,mechanics,slowmo",
    duration: "0:14",
    slug: "max-scherzer-ground-force-application-9",
    org_source: "https://www.youtube.com/shorts/MaYpO3s0LwQ",
    date_added: "4/3/2026",
    player: "Max Scherzer",
  },
];
